# Generated by Django 3.2.13 on 2022-06-12 19:57

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IRR', max_digits=15, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='لطفا نام کالا را وارد نمایید', max_length=200, verbose_name='عنوان'),
        ),
    ]
